name: Selenium Grid CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Docker Compose (Grid)
        run: docker compose up -d

      - name: Wait for Grid
        run: sleep 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Tests
        run: mvn test -DsuiteXmlFile=Master.xml
        env:
          GRID_URL: http://localhost:4444

      - name: Stop Grid
        if: always()
        run: docker compose down
